import type { Metadata } from "next";
import localFont from "next/font/local";

import "@/theme/global.css";
import "@/theme/icons.css";

const roboto = localFont({
  src: [
    {
      path: "../fonts/roboto-v32-latin-300.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/roboto-v32-latin-600.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/roboto-v32-latin-900.ttf",
      weight: "900",
      style: "normal",
    },
  ]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
