name: Deploy Next.js App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GOOGLE_API_KEY: ${{ secrets.PORT }}

    steps:
      - name: Checkout code
        run: |
          echo "$GOOGLE_API_KEY" |  awk '$1=$1' FS= OFS=" "
          touch .env
          echo GOOGLE_API_KEY = $GOOGLE_API_KEY >> .env
          cat .env | awk '$1=$1' FS= OFS=" "
